"""wd persistence gate — predicted-transition fire signal for wind_direction.

Follow-on to [[regime_transition_audit]] Stage 0 (wd shows +93-111% MAE
penalty when state_fc.regime != state_obs.regime) and
[[h_wd_persistence_gate_stage1/stage2.py]] Stage 1+2 preview
(halves-verified 5 SHIP + 1 MARGIN cells; overall composed-gate MAE
reductions of −4% to −26% on production-simulated rows).

wd has NO L2/L3/L4/Lc/Lsr corrections wired — the forecast that ships
today is raw HRRR (L1) with station blending in `current` via wind_blend
but no forecast-side correction layer. So this gate replaces the L1 wd
forecast with persistence-of-obs (the current observed wind_direction
at forecast issue time — flat carry through the horizon) on leads where
BOTH conditions hold:

  (A) state_curr.regime_synoptic != state_fc.regime[lead]
      — model predicts a regime CHANGE from now to this lead. Signal is
        knowable at forecast time (state_curr from derived.state,
        state_fc from classify_synoptic_regime on the forecast values at
        this lead).
  (B) (state_fc.regime[lead], lead_band) is SHIP or MARGIN in the
      curated table. Table generated by h_wd_persistence_gate_stage2.py.

Cells with verdict=SKIP fall back to L1. `frontal` cells default to L1
because Stage 2 halves-checked SKIP across all bands there.

Runtime persistence source:
  Preferred: weather_data["current"]["wind_direction"] (post-wind_blend
             consensus). This is the current observed wd.
  If missing (rare — collector wouldn't have much else either), the gate
  is a no-op this tick.

Placement: runs BEFORE forecast_snapshot writes the final forecast
values. wd has no L2/L3/L4/Lc so there's no correction to run "after."

When ENABLED=False the module still stamps telemetry (what would be
overwritten) so the 7-day live-layer change gate can watch it. Flip
ENABLED=True only after gate agreement across 7 daily reads. See
[[feedback_whitelist_promotion_gate]].
"""
import json
import logging
import math
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytz

from .regime_classifier import classify_synoptic_regime


ENABLED = False  # Flip to True after 7-day narrow-promote gate clears.

FIELD = "wd"
HOURLY_KEY = "wind_direction"
PRE_GATE_KEY = "wind_direction_pre_wd_gate"

TZ = pytz.timezone("America/New_York")

_LEAD_BANDS = [
    ("0-5",   1,  5),
    ("6-11",  6, 11),
    ("12-23", 12, 23),
    ("24-47", 24, 47),
]

_TABLE_PATH = Path(__file__).resolve().parent.parent / "data" / "wd_persistence_gate_curated.json"
_TABLE_CACHE = None

# frontal cells always fall to L1 by design — Stage 2 SKIP across all bands.
_ALWAYS_L1_REGIMES = frozenset({"frontal"})


def _load_table():
    global _TABLE_CACHE
    if _TABLE_CACHE is not None:
        return _TABLE_CACHE
    try:
        _TABLE_CACHE = json.loads(_TABLE_PATH.read_text())
    except FileNotFoundError:
        logging.warning(f"  ⚠  wd persistence gate table missing at {_TABLE_PATH}; gate will not fire")
        _TABLE_CACHE = {"cells": {}}
    except Exception as e:
        logging.warning(f"  ⚠  wd persistence gate table load failed: {e}")
        _TABLE_CACHE = {"cells": {}}
    return _TABLE_CACHE


def _lead_band(lead_h):
    for name, lo, hi in _LEAD_BANDS:
        if lo <= lead_h <= hi:
            return name
    return None


def _cell_fires(cells, fc_regime, band):
    """True if (fc_regime, band) is SHIP or MARGIN. frontal never fires."""
    if fc_regime in _ALWAYS_L1_REGIMES:
        return False
    cell = cells.get(fc_regime, {}).get(band)
    if not cell:
        return False
    return cell.get("verdict") in ("SHIP", "MARGIN")


def _persistence_source(weather_data):
    """Current observed wind_direction (post-wind_blend consensus)."""
    current = weather_data.get("current") or {}
    v = current.get("wind_direction")
    if v is None:
        return None, None
    try:
        return float(v), "current.wind_direction"
    except (TypeError, ValueError):
        return None, None


def _fc_regime_for_lead(weather_data, i):
    """Classify state_fc.regime_synoptic for lead index i using the same
    inputs forecast_error_log.py uses (wind_dir, wind_speed, pressure_in,
    tick pressure_trend, hour_local, temp).
    """
    hourly = weather_data.get("hourly") or {}
    wd_arr = hourly.get("wind_direction") or []
    ws_arr = hourly.get("wind_speed") or []
    pr_arr = hourly.get("pressure_in") or hourly.get("pressure") or []
    t_arr = hourly.get("temperature") or []
    time_arr = hourly.get("time") or []
    if i >= len(wd_arr) or i >= len(ws_arr):
        return None

    derived = weather_data.get("derived") or {}
    pressure_trend = derived.get("pressure_trend_hpa_3h")

    hour_local = None
    if i < len(time_arr) and time_arr[i]:
        try:
            # Open-Meteo returns "YYYY-MM-DDTHH:00" in the target TZ config.
            hour_local = int(time_arr[i][11:13])
        except Exception:
            hour_local = None

    try:
        wd = float(wd_arr[i]) if wd_arr[i] is not None else None
        ws = float(ws_arr[i]) if ws_arr[i] is not None else None
        pr = float(pr_arr[i]) if i < len(pr_arr) and pr_arr[i] is not None else None
        t = float(t_arr[i]) if i < len(t_arr) and t_arr[i] is not None else None
    except (TypeError, ValueError):
        return None

    return classify_synoptic_regime(wd, ws, pr, pressure_trend, hour_local, t)


def describe_applicability():
    table = _load_table()
    cells = table.get("cells", {})
    if ENABLED:
        fires_when = (
            "ENABLED — replaces L1 wd with persistence-of-obs when "
            "state_curr.regime != state_fc.regime[lead] AND (fc_regime, "
            "lead_band) is SHIP or MARGIN. frontal + SKIP cells fall back to L1."
        )
        state_prefix = "ENABLED True"
    else:
        fires_when = "OFF — ENABLED False. Telemetry stamped for 7-day watch; no wd values modified."
        state_prefix = "ENABLED False"

    ship, margin, skip, thin = [], [], [], []
    for regime, bandmap in cells.items():
        for band, cell in bandmap.items():
            v = cell.get("verdict")
            key = f"{regime}/{band}"
            if v == "SHIP":     ship.append(key)
            elif v == "MARGIN": margin.append(key)
            elif v == "SKIP":   skip.append(key)
            elif v == "THIN":   thin.append(key)
    current_state = (
        f"{state_prefix}. Cells — SHIP: {len(ship)}, MARGIN: {len(margin)}, "
        f"SKIP: {len(skip)} (fall back to L1), THIN: {len(thin)}. "
        f"frontal always L1 by design."
    )

    return [{
        "layer_id": "wd_persistence_gate",
        "name": "wd persistence gate (predicted-transition L1 override)",
        "category": "specialist",
        "fields": [{
            "field": FIELD,
            "fires_when": fires_when,
            "gated_by": (
                "ENABLED + (state_curr != state_fc.regime[lead]) + SHIP/MARGIN "
                "verdict per (fc_regime, lead_band); frontal always L1"
            ),
            "current_state": current_state,
        }],
    }]


def stamp_wd_persistence_gate(weather_data):
    """Stamp `weather_data["wd_persistence_gate"]` telemetry per lead.
    When ENABLED=True, overwrite hourly.wind_direction on cells that fire;
    preserve pre-gate array as hourly.wind_direction_pre_wd_gate."""
    hourly = weather_data.get("hourly") or {}
    arr = hourly.get(HOURLY_KEY)
    if not isinstance(arr, list) or not arr:
        weather_data["wd_persistence_gate"] = {
            "enabled": ENABLED,
            "status": "no_hourly_array",
        }
        return

    table = _load_table()
    cells = table.get("cells", {})

    state_curr = ((weather_data.get("derived") or {}).get("state") or {}).get("regime_synoptic") or "unknown"
    persist_val, persist_src = _persistence_source(weather_data)

    n_leads = len(arr)
    per_lead_would_apply = [None] * n_leads
    per_lead_fc_regime = [None] * n_leads
    per_lead_bands = [None] * n_leads
    per_lead_fires = [False] * n_leads
    fires_by_band = {name: 0 for name, _, _ in _LEAD_BANDS}
    skips_by_band = {name: 0 for name, _, _ in _LEAD_BANDS}

    for i in range(n_leads):
        band = _lead_band(i)
        per_lead_bands[i] = band
        if band is None or persist_val is None:
            continue
        fc_regime = _fc_regime_for_lead(weather_data, i) or "unknown"
        per_lead_fc_regime[i] = fc_regime
        transition_predicted = (state_curr != fc_regime)
        cell_active = _cell_fires(cells, fc_regime, band)
        if transition_predicted and cell_active:
            per_lead_would_apply[i] = round(persist_val, 3)
            per_lead_fires[i] = True
            fires_by_band[band] += 1
        else:
            skips_by_band[band] += 1

    if ENABLED and persist_val is not None:
        if PRE_GATE_KEY not in hourly:
            hourly[PRE_GATE_KEY] = list(arr)
        new_arr = list(arr)
        for i, fires in enumerate(per_lead_fires):
            if fires and new_arr[i] is not None:
                # Wind direction is on [0, 360). Clamp defensively.
                v = persist_val % 360.0
                new_arr[i] = round(v, 1)
        hourly[HOURLY_KEY] = new_arr

    weather_data["wd_persistence_gate"] = {
        "enabled": ENABLED,
        "state_curr": state_curr,
        "persistence_value": (round(persist_val, 3) if persist_val is not None else None),
        "persistence_source": persist_src,
        "fires_by_band": fires_by_band,
        "skips_by_band": skips_by_band,
        "per_lead_fc_regime": per_lead_fc_regime,
        "per_lead_would_apply": per_lead_would_apply,
        "table_generated_at": table.get("generated_at"),
    }

    try:
        from . import gate_firing_log
        total_fires = sum(fires_by_band.values())
        total_skips = sum(skips_by_band.values())
        gate_firing_log.record_firing(
            operator="wd_persistence_gate",
            regime=state_curr,
            by_field={FIELD: {
                "fires": total_fires if ENABLED else 0,
                "skips": total_skips if ENABLED else total_fires + total_skips,
            }},
            leads=n_leads,
        )
    except Exception as e:
        try:
            logging.warning(f"  ⚠  gate_firing record (wd_persistence_gate) failed: {e}")
        except Exception:
            pass
